# Snowflake Native App Configuration for SPCS
definition_version: 1
native_app:
  name: snowflake_ontology_engine
  artifacts:
    - src: backend/*
      dest: backend/
    - src: frontend/*
      dest: frontend/
    - src: sql/*
      dest: sql/

# Service specification for SPCS
services:
  - name: ontology-backend
    image: backend:latest
    compute_pool: ONTOLOGY_COMPUTE_POOL
    min_instances: 1
    max_instances: 3
    spec:
      containers:
        - name: backend
          image: /ontology_db/public/ontology_backend_image:latest
          env:
            SNOWFLAKE_ACCOUNT: 
              from_snowflake: CURRENT_ACCOUNT()
            SNOWFLAKE_USER:
              from_snowflake: CURRENT_USER()
            SNOWFLAKE_WAREHOUSE: COMPUTE_WH
            SNOWFLAKE_DATABASE: ONTOLOGY_DB
            SNOWFLAKE_SCHEMA: PUBLIC
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 2
      endpoints:
        - name: api
          port: 8000
          public: true

  - name: ontology-frontend
    image: frontend:latest
    compute_pool: ONTOLOGY_COMPUTE_POOL
    min_instances: 1
    max_instances: 3
    spec:
      containers:
        - name: frontend
          image: /ontology_db/public/ontology_frontend_image:latest
          env:
            VITE_API_URL: http://ontology-backend:8000
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
      endpoints:
        - name: web
          port: 80
          public: true
